pywren: 
    storage_bucket: <CONTAINER_NAME>
    storage_backend: azure_blob
    compute_backend: azure_fa
    #rabbitmq_monitor: <True/False>
    #remote_invoker: <True/False>
    #data_cleaner: <True/False>
    #workers: <MAX_NUM_OF_WORKERS>

azure_blob:
    account_name : <STORAGE_ACCOUNT_NAME>
    account_key  : <STORAGE_ACCOUNT_KEY>

azure_fa:
    resource_group: <RESOURCE_GROUP>
    location : <CONSUMPTION_PLAN_LOCATION>
    account_name : <STORAGE_ACCOUNT_NAME>
    account_key  : <STORAGE_ACCOUNT_KEY>
    #functions_version : <AZURE_FUNCTIONS_VERSION>  # default = 2.0

#rabbitmq:
    #amqp_url 	: <RABBIT_AMQP_URL>  # amqp://
